#!/bin/bash

# Default ENV settings
TARGET_DIR=/home
QUEST_NAME=$1

if [ -z "$1" ]; then
  echo "Please provide a quest name."
  exit 1
fi

for dir in $TARGET_DIR/*; do 
   if [ -d "$dir" ]; then
     user=$(basename "$dir")
   else
     break
   fi

   if [[ $user == "user-*" ]]; then
     if [ -L "./quest-report/$QUEST_NAME" ]; then
       mdkir ./quest-report/$QUEST_NAME
     fi

     test_result=$(./quest-solution/$QUEST_NAME/test-suite $user)
     echo "$user,$test_result" >> ./quest-report/"$QUEST_NAME.csv"
   fi
done

