#!/bin/bash

# Default ENV settings
TARGET_DIR=/home
QUEST_NAME=$1
REPORT_CSV=./quest-report/"$QUEST_NAME.csv"
REPORT_JSON=./quest-report/"$QUEST_NAME.json"

VISUALISER_REPORT_JSON=./visualizer/database/"$QUEST_NAME-report.json"

if [ -z "$1" ]; then
  echo "Please provide a quest name."
  exit 1
fi

# Clear previous state
rm -f $REPORT_CSV
rm -f $REPORT_JSON

echo "username,testResult" > $REPORT_CSV
for dir in $TARGET_DIR/*; do 
   if [ -d "$dir" ]; then
     user=$(basename "$dir")
   else
     break
   fi

   if [[ $user == user-* ]]; then
     test_result=$(./quest-solution/$QUEST_NAME/test-suite $user)
     echo "$user,$test_result" >> $REPORT_CSV
   fi
done

# Report in sorted CSV format
sort -V $REPORT_CSV -o $REPORT_CSV

# Report in JSON format
awk -F, '
NR==1 {
    for (i=1; i<=NF; i++) header[i] = $i;
}
NR>1 {
    printf "{";
    for (i=1; i<=NF; i++) {
        printf "\"%s\": \"%s\"", header[i], $i;
        if (i < NF) printf ", ";
    }
    print "}";
} 
' $REPORT_CSV > "$REPORT_JSON.tmp"
jq -s '.' "$REPORT_JSON.tmp" > $REPORT_JSON
rm -f "$REPORT_JSON.tmp"

ln $REPORT_JSON > $VISUALISER_REPORT_JSON
