#!/bin/bash

# Default ENV settings
SEPERATOR=-----------------------------------
SALT=linux

if [ -z "$1" ]; then
  echo "Please provide a number of generating user."
  exit 1
fi

COUNT=$1

for ((i=1; i<=COUNT; i++)); do 
   last_user_number=$(ls /home | grep user | nl | awk -F ' ' 'END {print $1}')
   new_user="user-$((last_user_number + 1))"
   new_user_password=$(echo "SEED" | openssl passwd -1 -stdin)
   
   # Adding new user to the server.
   # ONLY STDERR can be seen in this command.
   sudo useradd -m -p $new_user_password $new_user > /dev/null 2>&1
   
   # Giving a starter pack for new user
   sudo cp -r ./starter-pack/* /home/$new_user/
   sudo chown -R $new_user:$new_user /home/$new_user/*
   
   # Generate user information
   echo $SEPERATOR >> users
   echo $new_user >> users
   echo $new_user_password >> users
   echo $SEPERATOR >> users
done
