#!/bin/bash

USER=$1
QUEST=quest-8
ANSWERS=answers


is_read_and_write_perm_correct=0
is_executable_perm_correct=0

read_and_write_path=/home/$USER/$QUEST/$ANSWERS/read_and_write
if [ -e "$read_and_write_path" ]; then
  perm=$(ls -l $read_and_write_path | awk '{print $1}' 2> /dev/null )
  if [ "$perm" = "-rw-rw----" ]; then
    is_read_and_write_perm_correct=1
  fi
fi

executable_path=/home/$USER/$QUEST/$ANSWERS/executable_file
if [ -e "$executable_path" ]; then
  perm=$(ls -l $executable_path | awk '{print $1}' 2> /dev/null )
  if [ "$perm" = "-rwx--x--x" ]; then
    is_executable_perm_correct=1
  fi
fi


if [ $is_read_and_write_perm_correct = 1 ] && [ $is_executable_perm_correct = 1 ]; then
  echo PASSED
else
  echo FAILED
fi

