#!/bin/bash

USER=$1
QUEST=quest-6
ANSWERS=answers
CURRENT_DIR=$(dirname "$(realpath "$0")")

is_rock_pokemon_file_exist=0
is_first_10_dragon_file_exist=0

rock_pokemon_path=/home/$USER/$QUEST/$ANSWERS/rock_pokemon.csv
if [ -e  "$rock_pokemon_path" ]; then

  cmp $CURRENT_DIR/rock_pokemon.csv $rock_pokemon_path 2> /dev/null
  if [ ! $? -eq 1 ]; then
    is_rock_pokemon_file_exist=1
  fi
fi

first_10_dragon_path=/home/$USER/$QUEST/$ANSWERS/first_10_dragon_pokemon.csv
if [ -e  "$first_10_dragon_path" ]; then

  cmp $CURRENT_DIR/first_10_dragon_pokemon.csv $first_10_dragon_path 2> /dev/null
  if [ ! $? -eq 1 ]; then
    is_first_10_dragon_file_exist=1
  fi
fi


if [ $is_rock_pokemon_file_exist = 1 ] && [ $is_first_10_dragon_file_exist = 1 ]; then
  echo PASSED
else
  echo FAILED
fi
