#!/bin/bash

USER=$1
QUEST=quest-4
ANSWERS=answers
CURRENT_DIR=$(dirname "$(realpath "$0")")


is_operating_system_dir_exist=0
is_mac_window_linux_exist=0
is_leo_removed=0
is_unix_exist_in_os_dir=0

operating_system_path=/home/$USER/$QUEST/$ANSWERS/operating_system
if [ -d  "$operating_system_path" ]; then
    is_operating_system_dir_exist=1
fi

mac_path=$operating_system_path/mac
window_path=$operating_system_path/window
linux_path=$operating_system_path/linux
if [ -d  "$mac_path" ] && [ -d "$window_path" ] && [ -d "$linux_path" ]; then
  is_mac_window_linux_exist=1
fi

leo_path=/home/$USER/$QUEST/$ANSWERS/leo
if [ ! -d  "$leo_path" ]; then
    is_leo_removed=1
fi

unix_path=$operating_system_path/unix
if [ -d  "$unix_path" ]; then
  is_unix_exist_in_os_dir=1
fi

if [ $is_operating_system_dir_exist = 1 ] && [ $is_mac_window_linux_exist = 1 ] && [ $is_leo_removed = 1 ] && [ $is_unix_exist_in_os_dir = 1 ]; then
  echo PASSED
else
  echo FAILED
fi
