#!/bin/bash

USER=$1
QUEST=quest-10
ANSWERS=answers


is_readme_exist=0

readme_path=/home/$USER/$QUEST/$ANSWERS/readme
if [ -e  "$readme_path" ]; then
  is_readme_exist=1
fi

if [ $is_readme_exist = 1 ]; then
  echo PASSED
else
  echo FAILED
fi

