#!/bin/bash

USER=$1
QUEST=quest-9
ANSWERS=answers


is_all_answers_files_perm_correct=1

answers_path=/home/$USER/$QUEST/$ANSWERS
if [ -e "$answers_path" ]; then
  for p in $(ls -l $answers_path | awk 'NR > 1 {print $1}'); do 
    if [ ! "$p" = "-rwxrw----" ]; then
      is_all_answers_files_perm_correct=0
    fi
  done
fi

if [ $is_all_answers_files_perm_correct = 1 ]; then
  echo PASSED
else
  echo FAILED
fi

