#!/bin/bash

USER=$1
QUEST=quest-7
ANSWERS=answers
CURRENT_DIR=$(dirname "$(realpath "$0")")

is_bird_animals_file_exist=0
is_sorted_bird_animals_file_exist=0

bird_animals_path=/home/$USER/$QUEST/$ANSWERS/bird_animals.csv
if [ -e  "$bird_animals_path" ]; then

  cmp $CURRENT_DIR/bird_animals.csv $bird_animals_path 2> /dev/null
  if [ ! $? -eq 1 ]; then
    is_bird_animals_file_exist=1
  fi
fi

sorted_bird_animals_path=/home/$USER/$QUEST/$ANSWERS/sorted_bird_animals.csv
if [ -e  "$sorted_bird_animals_path" ]; then

  cmp $CURRENT_DIR/sorted_bird_animals.csv $sorted_bird_animals_path 2> /dev/null
  if [ ! $? -eq 1 ]; then
    is_sorted_bird_animals_file_exist=1
  fi
fi


if [ $is_bird_animals_file_exist = 1 ] && [ $is_sorted_bird_animals_file_exist = 1 ]; then
  echo PASSED
else
  echo FAILED
fi
