#!/bin/bash

USER=$1
QUEST=quest-5
ANSWERS=answers
CURRENT_DIR=$(dirname "$(realpath "$0")")


is_unix_removed=0
is_empty_dir_empty=0

unix_path=/home/$USER/$QUEST/$ANSWERS/unix
if [ ! -d  "$unix_path" ]; then
  is_unix_removed=1
fi

empty_dir_path=/home/$USER/$QUEST/$ANSWERS/empty_dir
if [ -d  "$empty_dir_path" ]; then
  if [ -z "$(ls $empty_dir_path 2> /dev/null)" ]; then
    is_empty_dir_empty=1
  fi
fi

if [ $is_unix_removed = 1 ] && [ $is_empty_dir_empty = 1 ]; then
  echo PASSED
else
  echo FAILED
fi
